version: "3.8"

services: 
  postgresql:
    image: postgres:latest
    env_file:
      - ./config/db/env
    volumes: 
      - "./config/db/init.sql:/docker-entrypoint-initdb.d/"
      - "data:/var/lib/postgresql/data"

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    env_file:
      - ./config/app/.env
    depends_on: 
      - postgresql

volumes: 
  data: