version: "3.8"

services:
    db:
        image: postgres
        volumes: 
            - "data:/var/lib/postgresql/data"
            - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
        environment: 
            POSTGRES_PASSWORD: postgres
        networks: 
            - my-app
    web:
        build: .
        ports:
            - 8181:8080
        depends_on: 
            - db
        networks: 
            - my-app

networks:
    my-app:

volumes:
    data: