version: "3.8"

services: 
  db:
    image : mysql:5.7
    container_name: db
    networks: 
      - ghost-network
    volumes: 
      - "blog_data:/var/lib/mysql"
    environment: 
      - MYSQL_ROOT_PASSWORD=example

  app:
    image: ghost:alpine
    container_name: ghost-app
    restart: on-failure
    ports: 
      - "8088:2368"
    networks: 
      - ghost-network
    depends_on:
      - db
    environment: 
      - database__client=mysql
      - database__connection__host=db
      - database__connection__user=root
      - database__connection__password=example
      - database__connection__database=ghost

networks: 
  ghost-network:
    external: true

volumes: 
  blog_data:

    