version: "3.8"

services: 
  mysql:
    image : mysql:5.7
    networks: 
      - ghost-network
    volumes: 
      - "blog_data:/var/lib/mysql"
    environment: 
      - MYSQL_ROOT_PASSWORD=example

  app:
    image: ghost:alpine
    ports: 
      - "8088:2368"
    networks: 
      - ghost-network
    depends_on:
      - mysql

networks: 
  ghost-network:
    external: true

volumes: 
  blog_data:

    